In [23]:
help()   ## 도움말 검색
# NUMpy example ref site : http://cs231n.github.io/python-numpy-tutorial/
# https://github.com/insightbook/Data-Science-from-Scratch


Welcome to Python 3.6's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at http://docs.python.org/3.6/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [2]:
help(pylab)

NameError: name 'pylab' is not defined

In [3]:
help(plot)

NameError: name 'plot' is not defined

In [4]:
fill(t,s,’b’, t,c,’g’, alpha=0.2)

SyntaxError: invalid character in identifier (<ipython-input-4-6b6e8a8c72ec>, line 1)

In [5]:
import simpy

ModuleNotFoundError: No module named 'simpy'

In [6]:
##C:\stock>pip install simpy   < --- simpy 설치하는 방법 
#Collecting simpy
#  Downloading simpy-3.0.10-py2.py3-none-any.whl
#Installing collected packages: simpy
#Successfully installed simpy-3.0.10

# ref site : https://simpy.readthedocs.io/en/latest/

SyntaxError: unexpected character after line continuation character (<ipython-input-6-0c6ce1455c97>, line 1)

In [7]:
import simpy

In [8]:
def clock(env, name, tick):
    while True:
        print(name, env.now)
        yield env.timeout(tick)

In [9]:
env = simpy.Environment()

In [10]:
env.process(clock(env, 'fast', 0.5))

<Process(clock) object at 0x25c4f19aa58>

In [11]:
env.process(clock(env, 'slow', 1))

<Process(clock) object at 0x25c4f19aa20>

In [12]:
 env.run(until=2)

fast 0
slow 0
fast 0.5
slow 1
fast 1.0
fast 1.5


In [13]:
a == b or equal(a,b)

NameError: name 'a' is not defined

In [14]:
theta = arange(0,2*pi,0.001)
r = sin(2*theta)


NameError: name 'arange' is not defined

In [15]:
import numpy
np.spacing(1)

NameError: name 'np' is not defined

In [16]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


- Booleans

In [17]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


- Strings: Python has great support for strings:

In [18]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


- String objects have a bunch of useful methods; for example:

In [19]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [ ]:
# Functions

# Python functions are defined using the def keyword. For example:


In [20]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


### Numpy

#### Arrays

In [21]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
## Array indexing

In [22]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [24]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


In [25]:
import numpy as np

In [28]:
 a = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))

In [29]:
a = np.r_[3,[0]*5,-1:1:10j]

In [30]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [31]:
np.mgrid[0:5:4j,0:5:4j]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.66666667,  1.66666667,  1.66666667,  1.66666667],
        [ 3.33333333,  3.33333333,  3.33333333,  3.33333333],
        [ 5.        ,  5.        ,  5.        ,  5.        ]],

       [[ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ],
        [ 0.        ,  1.66666667,  3.33333333,  5.        ]]])

In [32]:
from numpy import poly1d

In [33]:
p = poly1d([3,4,5])

In [37]:
x, y, z, value = np.random.random((4, 40))
mlab.points3d(x, y, z, value)

NameError: name 'mlab' is not defined

In [40]:
[i**2 for i in range(4)]
#[0, 1, 4, 9]

[0, 1, 4, 9]

In [44]:
import pandas
data = pandas.read_csv('examples/brain_size.csv', sep=';', na_values=".")

In [45]:
data

Unnamed: 0  Gender  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count
0            1  Female   133  132  124   118.0    64.5     816932
1            2    Male   140  150  124     NaN    72.5    1001121
2            3    Male   139  123  150   143.0    73.3    1038437
3            4    Male   133  129  128   172.0    68.8     965353
4            5  Female   137  132  134   147.0    65.0     951545
5            6  Female    99   90  110   146.0    69.0     928799
6            7  Female   138  136  131   138.0    64.5     991305
7            8  Female    92   90   98   175.0    66.0     854258
8            9    Male    89   93   84   134.0    66.3     904858
9           10    Male   133  114  147   172.0    68.8     955466
10          11  Female   132  129  124   118.0    64.5     833868
11          12    Male   141  150  128   151.0    70.0    1079549
12          13    Male   135  129  124   155.0    69.0     924059
13          14  Female   140  120  147   155.0    70.5     856472
14          15  Female    96  100   90   146.0    66.0     878897
15          16  Female    83   71   96   135.0    68.0     865363
16          17  Female   132  132  120   127.0    68.5     852244
17          18    Male   100   96  102   178.0    73.5     945088
18          19  Female   101  112   84   136.0    66.3     808020
19          20    Male    80   77   86   180.0    70.0     889083
20          21    Male    83   83   86     NaN     NaN     892420
21          22    Male    97  107   84   186.0    76.5     905940
22          23  Female   135  129  134   122.0    62.0     790619
23          24    Male   139  145  128   132.0    68.0     955003
24          25  Female    91   86  102   114.0    63.0     831772
25          26    Male   141  145  131   171.0    72.0     935494
26          27  Female    85   90   84   140.0    68.0     798612
27          28    Male   103   96  110   187.0    77.0    1062462
28          29  Female    77   83   72   106.0    63.0     793549
29          30  Female   130  126  124   159.0    66.5     866662
30          31  Female   133  126  132   127.0    62.5     857782
31          32    Male   144  145  137   191.0    67.0     949589
32          33    Male   103   96  110   192.0    75.5     997925
33          34    Male    90   96   86   181.0    69.0     879987
34          35  Female    83   90   81   143.0    66.5     834344
35          36  Female   133  129  128   153.0    66.5     948066
36          37    Male   140  150  124   144.0    70.5     949395
37          38  Female    88   86   94   139.0    64.5     893983
38          39    Male    81   90   74   148.0    74.0     930016
39          40    Male    89   91   89   179.0    75.5     935863

In [47]:
import numpy as np
t = np.linspace(-6, 6, 20)
sin_t = np.sin(t)
cos_t = np.cos(t)

In [48]:
pandas.DataFrame({'t': t, 'sin': sin_t, 'cos': cos_t}) 

cos       sin         t
0   0.960170  0.279415 -6.000000
1   0.609977  0.792419 -5.368421
2   0.024451  0.999701 -4.736842
3  -0.570509  0.821291 -4.105263
4  -0.945363  0.326021 -3.473684
5  -0.955488 -0.295030 -2.842105
6  -0.596979 -0.802257 -2.210526
7  -0.008151 -0.999967 -1.578947
8   0.583822 -0.811882 -0.947368
9   0.950551 -0.310567 -0.315789
10  0.950551  0.310567  0.315789
11  0.583822  0.811882  0.947368
12 -0.008151  0.999967  1.578947
13 -0.596979  0.802257  2.210526
14 -0.955488  0.295030  2.842105
15 -0.945363 -0.326021  3.473684
16 -0.570509 -0.821291  4.105263
17  0.024451 -0.999701  4.736842
18  0.609977 -0.792419  5.368421
19  0.960170 -0.279415  6.000000

In [49]:
data.shape

(40, 8)

In [50]:
data.columns

Index(['Unnamed: 0', 'Gender', 'FSIQ', 'VIQ', 'PIQ', 'Weight', 'Height',
       'MRI_Count'],
      dtype='object')

In [51]:
print(data['Gender'])

0     Female
1       Male
2       Male
3       Male
4     Female
5     Female
6     Female
7     Female
8       Male
9       Male
10    Female
11      Male
12      Male
13    Female
14    Female
15    Female
16    Female
17      Male
18    Female
19      Male
20      Male
21      Male
22    Female
23      Male
24    Female
25      Male
26    Female
27      Male
28    Female
29    Female
30    Female
31      Male
32      Male
33      Male
34    Female
35    Female
36      Male
37    Female
38      Male
39      Male
Name: Gender, dtype: object


In [52]:
data[data['Gender'] == 'Female']['VIQ'].mean()

109.45

In [53]:
groupby_gender = data.groupby('Gender')
for gender, value in groupby_gender['VIQ']:
     print((gender, value.mean()))

('Female', 109.45)
('Male', 115.25)


In [54]:
groupby_gender.mean()

Unnamed: 0   FSIQ     VIQ     PIQ      Weight     Height  MRI_Count
Gender                                                                     
Female       19.65  111.9  109.45  110.45  137.200000  65.765000   862654.6
Male         21.35  115.0  115.25  111.60  166.444444  71.431579   954855.4

In [55]:
from pandas.tools import plotting

In [56]:
plotting.scatter_matrix(data[['Weight', 'Height', 'MRI_Count']])  

c:\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.
  """Entry point for launching an IPython kernel.


array([[<matplotlib.axes._subplots.AxesSubplot object at 0x0000025C52021908>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x0000025C517085C0>]], dtype=object)

In [57]:
plotting.scatter_matrix(data[['PIQ', 'VIQ', 'FSIQ']])   

c:\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'pandas.tools.plotting.scatter_matrix' is deprecated, import 'pandas.plotting.scatter_matrix' instead.
  """Entry point for launching an IPython kernel.


array([[<matplotlib.axes._subplots.AxesSubplot object at 0x0000025C52384CC0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x0000025C526C3E10>]], dtype=object)

In [61]:
from scipy import stats
stats.ttest_1samp(data['VIQ'], 0)   

Ttest_1sampResult(statistic=30.088099970849328, pvalue=1.3289196468728067e-28)

In [60]:
stats.ttest_1samp(data['VIQ'], 0)   
#(...30.088099970..., 1.32891964...e-28)

Ttest_1sampResult(statistic=30.088099970849328, pvalue=1.3289196468728067e-28)

In [66]:
import numpy as np
from statsmodels.formula.api import ols
data = pandas.read_csv('examples/iris.csv')

ModuleNotFoundError: No module named 'statsmodels'

In [67]:
model = ols('sepal_width ~ name + petal_length', data).fit()

NameError: name 'ols' is not defined